# Generated by Django 4.0.4 on 2022-06-01 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user_test',
            },
        ),
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=20)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow.usermodel')),
            ],
            options={
                'db_table': 'follow_test',
            },
        ),
    ]
